---
title: "11-bacterial_genome"
title-block-banner: true
author:
  - name: Jinlong Ru
    orcid: 0000-0002-6757-6018
date: 2024-12-08
toc: true
toc-depth: 4
number-sections: true
code-fold: true
code-line-numbers: true
code-tools: true
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    page-layout: full
reference-location: section
citation-location: document
params:
  name: "11-bacterial_genome"
---

```{r setup}
#| message: false
#| include: false
#| warning: false
setwd(here::here("analyses"))
params <- list(name = "11-bacterial_genome")
here::i_am(paste0(params$name, ".qmd"), uuid = "c5ca5f19-4770-4226-b501-460d26421fb8")
projthis::proj_create_dir_target(params$name, clean = FALSE)
path_target <- projthis::proj_path_target(params$name)
path_source <- projthis::proj_path_source(params$name)
path_raw <- path_source("00-raw")
path_resource <- here::here(path_raw, "d00-resource")
path_data <- here::here(path_raw, paste0("d", params$name))
dir.create(path_raw, recursive = TRUE, showWarnings = FALSE)
dir.create(path_data, recursive = TRUE, showWarnings = FALSE)
dir.create(path_resource, recursive = TRUE, showWarnings = FALSE)
```

## Tasks

1. The genome of *Aeromonas hydrophila* MS01 was assembled using [Unicycler](https://github.com/rrwick/Unicycler). 

2. Fragmented scaffolds were connected using [RagTag](https://github.com/malonge/RagTag) with *Aeromonas hydrophila* subsp. hydrophila ATCC 7966 as reference.

3. Assembled genome was annotated using [Bakta](https://github.com/oschwengers/bakta).

## Files written

These files have been written to the target directory, `r paste0("data/", params$name)`:

```{r list-files-target}
projthis::proj_dir_info(path_target(), tz = "CET")
```
