---
title: "113-tree"
date: today
params:
  name: "113-tree"
---

**Updated: `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'CET')` CET.**

```{r}
#| label: params
#| eval: !expr interactive()
#| include: false
params <- list(name = "113-tree")
```

```{r}
#| label: setup
#| include: false
#| message: false
#| warning: false
#| cache: false
wd <- "analyses"
if (basename(getwd()) != wd) {
    setwd(here::here(wd))
}
here::i_am(paste0(params$name, ".qmd"), uuid = "24d9ee92-87f0-437d-8a74-baacaab327c8")
qproj::proj_create_dir_target(params$name, clean = FALSE)

# convenience helpers
path_target <- qproj::proj_path_target(params$name)
path_source <- qproj::proj_path_source(params$name)
path_raw <- path_source("00-raw")
path_resource <- here::here(path_raw, "d00-resource")
path_data <- here::here(path_raw, paste0("d", params$name))
dir.create(path_raw, recursive = TRUE, showWarnings = FALSE)
dir.create(path_data, recursive = TRUE, showWarnings = FALSE)
dir.create(path_resource, recursive = TRUE, showWarnings = FALSE)
```

```{r}
#| label: packages
#| message: false
#| warning: false
#| cache: false
suppressPackageStartupMessages({
  library(here)
  library(conflicted)
  library(tidyverse)
  library(data.table)
  library(ggtree)
  library(ape)
  library(openxlsx)
  devtools::load_all()
})
# Resolve common dplyr / data.table / stats name clashes up front.
# Add more `conflicts_prefer()` calls below as needed.
conflicted::conflicts_prefer(
  dplyr::filter,
  dplyr::lag,
  dplyr::first,
  dplyr::last,
  dplyr::between,
  .quiet = TRUE
)
```

## Tasks

The first task is to import the NWK file containing the phylogenetic tree. The NWK file is downloaded from [NCBI BLAST Tree View](https://www.ncbi.nlm.nih.gov/blast/treeview/treeView.cgi?request=page&blastRID=FPB2S564014&queryID=lcl|Query_9661658&entrezLim=&ex=&exl=&exh=&ns=100&screenWidth=3440&screenHeight=1440).

```{r}
#| label: import-nwk
tree <- read.tree(here(path_data, "TLS_tree.nwk"))

# save the node data as an excel file, so that user can modify the node data manually and then import to the tree again

tip_data <- as.data.frame(tree$tip.label)
write.xlsx(tip_data, here(path_data, "tip_data.xlsx"), rowNames = TRUE)

# import the modified node data
modified_tip_data <- read.xlsx(here(path_data, "tip_data.xlsx"), rowNames = TRUE)
tree$tip.label <- modified_tip_data[, "name2"]

# plot new tree with the modified node labels
ggtree(tree) + geom_tiplab(aes(color =  str_detect(label, "vB_AhyM_Hp3"))) +
  scale_color_manual(values=c("black", "red")) + 
  xlim(0, 1.6) +
  theme(legend.position = "none")

# save the modified tree
ggsave(path_target( "TLS_tree.png"), width = 6.5, height = 4)
```

## Files written

These files have been written to the target directory, `r paste0("data/", params$name)`:

```{r}
#| label: list-files-target
knitr::kable(qproj::proj_dir_info(path_target(), tz = "CET"))
```
