---
title: "12-phage_genome"
title-block-banner: true
author:
  - name: Jinlong Ru
    orcid: 0000-0002-6757-6018
date: 2025-12-20
toc: true
toc-depth: 4
number-sections: true
code-fold: true
code-line-numbers: true
code-tools: true
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    page-layout: full
reference-location: section
citation-location: document
params:
  name: "12-phage_genome"
---

```{r}
#| label: params
#| eval: !expr interactive()
#| include: false
params = list(name = "12-phage_genome")
```

```{r}
#| label: setup
#| message: false
#| include: false
#| warning: false
wd <- "analyses"
if (basename(getwd()) != wd) {
  setwd(here::here(wd))
}
here::i_am(paste0(params$name, ".qmd"), uuid = "cd097d59-063f-4d07-8120-c6966ea882de")
projthis::proj_create_dir_target(params$name, clean = FALSE)
path_target <- projthis::proj_path_target(params$name)
path_source <- projthis::proj_path_source(params$name)
path_raw <- path_source("00-raw")
path_resource <- here::here(path_raw, "d00-resource")
path_data <- here::here(path_raw, paste0("d", params$name))
dir.create(path_raw, recursive = TRUE, showWarnings = FALSE)
dir.create(path_data, recursive = TRUE, showWarnings = FALSE)
dir.create(path_resource, recursive = TRUE, showWarnings = FALSE)
```

```{r}
#| label: packages
#| message: false
suppressPackageStartupMessages({
  library(here)
  library(tidyverse)
  library(data.table)
  library(geneviewer)
  devtools::load_all()
})
```

## Tasks

1. The genome of vB_AhyM_Hp3 was assembled using [Unicycler](https://github.com/rrwick/Unicycler). 

2. Assembled genome was annotated using [Pharokka](https://github.com/gbouras13/pharokka), [Phold](https://github.com/gbouras13/phold), and [phynteny](https://github.com/susiegriggo/Phynteny).

3. [vConTACT3](https://bitbucket.org/MAVERICLab/vcontact3) was used to cluster vB_AhyM_Hp3 with NCBI viral RefSeq genomes.

```{r}
#| label: gbk-to-tsv

file_gbk <- here(path_data, "phynteny.gbk")
gbk <- read_gbk(file_gbk)

# update the gbk file: if the`function` == "unknown function" and phynteny exists but not equal to "other", then update the `function` with phynteny
gbk$phynteny$FEATURES$CDS <- purrr::map(gbk$phynteny$FEATURES$CDS, ~ {

  phynteny    <- purrr::pluck(.x, "phynteny",  .default = "other")
  func_value  <- purrr::pluck(.x, "function",  .default = NA_character_)
  if (func_value == "unknown function" && phynteny != "other") {
    .x[["function"]] <- phynteny
  }
  return(.x)
})

df_cds <- gbk$phynteny$FEATURES$CDS %>%
  purrr::map_dfr(~ {
    list(
      locus_tag   = purrr::pluck(.x, "locus_tag",   .default = NA_character_),
      translation = purrr::pluck(.x, "translation", .default = NA_character_),
      region      = purrr::pluck(.x, "region",      .default = NA_character_),
      `function`  = purrr::pluck(.x, "function",    .default = NA_character_),
      product     = purrr::pluck(.x, "product",     .default = NA_character_)
    )
  }) %>%
  tidyr::separate(
    region,
    into = c("region_start", "region_end"),
    sep = "\\.\\.",
    convert = TRUE,
    fill = "right",
    extra = "merge"
  ) %>%
  dplyr::mutate(locus_tag = stringr::str_replace(locus_tag, "_CDS", ""))


fwrite(df_cds, path_target("phage_cds.tsv"), sep = "\t")
```

## Files written

These files have been written to the target directory, `r paste0("data/", params$name)`:

```{r}
#| label: list-files-target
#| include: false
projthis::proj_dir_info(path_target(), tz = "CET")
```
