#!/usr/bin/env python3
"""Generate LaTeX supplementary tables for the Hp3 manuscript from analysis TSVs.

Outputs (in this dir, \\input by supplementary.tex):
  si_table_orf.tex  -- Table S1: full Hp3 ORF / genome annotation (105 ORFs)
  si_table_sg.tex   -- Table S4: ViPTree whole-proteome similarity (S_G) to Hp3

Inputs live in the gitignored Dropbox data tree (analyses/data is a symlink):
  submit/submit-fsi/Hp3_ORF_annotation.tsv
  ICTV_proposal/03_similarity_matrices/viptree_SG_to_hp3.tsv

Re-run after the annotation or ViPTree outputs change:
  python3 make_si_tables.py
"""
import csv
import os
import sys

# analyses/data is a symlink to the Dropbox tree; resolve from the repo root.
DATA = os.path.expanduser("~/Dropbox/project/pc031-aquaPhage/data")
ORF_TSV = os.path.join(DATA, "submit/submit-fsi/Hp3_ORF_annotation.tsv")
SG_TSV = os.path.join(DATA, "ICTV_proposal/03_similarity_matrices/viptree_SG_to_hp3.tsv")

HERE = os.path.dirname(os.path.abspath(__file__))


def tex_escape(s):
    """Escape LaTeX special characters in plain-text fields."""
    if s is None:
        return ""
    repl = {
        "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
        "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    return "".join(repl.get(c, c) for c in s.strip())


def make_orf_table():
    rows = []
    with open(ORF_TSV, newline="") as fh:
        for r in csv.DictReader(fh, delimiter="\t"):
            start, end = int(r["region_start"]), int(r["region_end"])
            rows.append((
                tex_escape(r["locus_tag"]),
                f"{start:,}--{end:,}",
                f"{abs(end - start) + 1:,}",
                tex_escape(r["function"]),
                tex_escape(r["product"]),
            ))
    n_func = sum(1 for x in rows if x[3] not in ("unknown function", ""))
    out = []
    out.append("% AUTO-GENERATED by make_si_tables.py -- do not edit by hand.")
    out.append(r"\begin{small}")
    out.append(r"\begin{longtable}{@{}l l r p{0.22\linewidth} p{0.34\linewidth}@{}}")
    out.append(r"\caption{\textbf{Genome annotation of bacteriophage Hp3 "
               r"(vB\_AhyM\_Hp3).} All %d predicted open reading frames (ORFs) "
               r"of the 84{,}750\,bp genome (GenBank PX754746.1), with genomic "
               r"coordinates, length, PHROG functional category, and predicted "
               r"product. Annotation combined Pharokka, Phold, and Phynteny.}"
               r"\label{tbl-si-orf}\\" % len(rows))
    out.append(r"\toprule")
    head = (r"\textbf{Locus tag} & \textbf{Position (bp)} & \textbf{Length} & "
            r"\textbf{PHROG category} & \textbf{Predicted product}\\")
    out.append(head)
    out.append(r"\midrule")
    out.append(r"\endfirsthead")
    out.append(r"\toprule")
    out.append(head)
    out.append(r"\midrule")
    out.append(r"\endhead")
    out.append(r"\midrule \multicolumn{5}{r@{}}{\textit{continued on next page}}\\")
    out.append(r"\endfoot")
    out.append(r"\bottomrule")
    out.append(r"\endlastfoot")
    for lt, pos, length, func, prod in rows:
        out.append(f"{lt} & {pos} & {length} & {func} & {prod}\\\\")
    out.append(r"\end{longtable}")
    out.append(r"\end{small}")
    path = os.path.join(HERE, "si_table_orf.tex")
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"[ok] {path}  ({len(rows)} ORFs, {n_func} with assigned function)")


def make_sg_table(top_n=12):
    rows = []
    with open(SG_TSV, newline="") as fh:
        reader = csv.reader(fh, delimiter="\t")
        header = next(reader)
        sg_idx = next(i for i, h in enumerate(header) if "to hp3" in h)
        def clean(x):
            return x.strip() if x and x.strip() not in ("", "-") else ""

        for r in reader:
            if len(r) <= sg_idx:
                continue
            name = r[4].strip()
            if name.startswith("user_virus"):   # self-hit (Hp3 query), S_G = 1.0
                continue
            try:
                sg = float(r[sg_idx])
            except ValueError:
                continue
            grp = clean(r[8]) or clean(r[9]) or "unclassified"
            rows.append((r[0], name, grp, sg))
    rows.sort(key=lambda x: x[3], reverse=True)
    rows = rows[:top_n]
    out = []
    out.append("% AUTO-GENERATED by make_si_tables.py -- do not edit by hand.")
    out.append(r"\begin{table}[H]\centering")
    out.append(r"\caption{\textbf{Whole-proteome genomic similarity ($S_G$) of "
               r"the closest reference prokaryotic viruses to Hp3 (ViPTree).} "
               r"The maximum $S_G$ to any of the 5{,}633 reference dsDNA viruses "
               r"is only %.3f, to the unclassified \emph{Rhizobium} phage "
               r"vB\_RleS\_L338C, underscoring the isolated, deeply branching "
               r"position of Hp3 reported in the main text.}\label{tbl-si-sg}"
               % rows[0][3])
    out.append(r"\begin{small}")
    out.append(r"\begin{tabular}{@{}r l l r@{}}")
    out.append(r"\toprule")
    out.append(r"\textbf{Rank} & \textbf{Reference virus} & "
               r"\textbf{Family / host group} & \textbf{$S_G$ to Hp3}\\")
    out.append(r"\midrule")
    for i, (acc, name, grp, sg) in enumerate(rows, 1):
        out.append(f"{i} & {tex_escape(name)} & {tex_escape(grp)} & {sg:.3f}\\\\")
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    out.append(r"\end{small}")
    out.append(r"\end{table}")
    path = os.path.join(HERE, "si_table_sg.tex")
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"[ok] {path}  (top {len(rows)}; max S_G = {rows[0][3]:.3f})")


if __name__ == "__main__":
    missing = [p for p in (ORF_TSV, SG_TSV) if not os.path.exists(p)]
    if missing:
        sys.exit("Missing input(s):\n  " + "\n  ".join(missing))
    make_orf_table()
    make_sg_table()
